version: '3.7'
services:
  flask_app:
    # Собираем контейнер с приложением с помощью uwsgi.Dockerfile
    # Присваеваем имя контейнера "flask_app"

    # ******** НИЖЕ НАПИШИТЕ КОД ВЫПОЛНЯЮЩИЙ 2 ДЕЙСТВИЯ ОПИСАННЫЕ ВЫШЕ
    ## ........


  nginx_server:
    # Собираем контейнер с приложением с помощью /nginx/Dockerfile
    # Открываем 8000 порт для внешнего мира
    # Присваеваем имя контейнера "nginx_server"

    # ******** НИЖЕ НАПИШИТЕ КОД ВЫПОЛНЯЮЩИЙ 3 ДЕЙСТВИЯ ОПИСАННЫЕ ВЫШЕ
    ## ........

